export const MAX_N_BACK = 10;
export const ACTIVE_SQUARE_TIME = 1000;
export const NO_ACTIVE_SQUARE_TIME = 300;
export const ROUND_TIME = ACTIVE_SQUARE_TIME + NO_ACTIVE_SQUARE_TIME;
export const USER_FAILURE_TIME = 200;
export const USER_SUCCESS_TIME = USER_FAILURE_TIME;

export const ROUNDS = 25;
